<style>
.recipeIndexPage {
    float: left;
    width: 100%;
}
.recipeTableIndex {
    width: 100%;
}
.recipeTableIndex th {
    background-color: #CCCCCC;
    border: 1px solid #999999;
    color: #000000;
    font-family: Tahoma,Geneva,sans-serif;
    font-size: 12px;
    font-weight: bold;
    padding-bottom: 10px;
    padding-left: 12px;
    padding-top: 10px;
}
.recipeTableIndex tr {
    background-color: #FFFFFF;
}
.recipeTableIndex tr:hover {
    background-color: #0099CC;
}
.recipeTableIndex td {
    border: 1px solid #999999;
    padding-bottom: 10px;
    padding-left: 8px;
    padding-top: 10px;
    text-align: left;
}
table {
    margin: 5px 0;!important;
}
</style>
<div class="recipeIndexPage" >
	
     <table class="recipeTableIndex" cellpadding="0" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th  width="3%">S.No</th>
                <th width="12%">Date of Booking</th>
                <th width="12%">Property No.</th>
                <th width="12%">Check-in Date</th>
                <th width="12%">No. Of Nights</th>
                <th width="12%">Departure Date</th>
                <th width="12%">Status</th>
                <th width="6%">View</th>
            </tr>
        </thead>
        
        <tbody>
        <? $i=0; foreach($this->bookingData as $row) { $start++;$i++;
	    			    switch($row['paid_status'])
						{	case '0': $p_type ='Pending';  break;
							case '1': $p_type ='Advanced';  break;
							case '2': $p_type ='Full';  break;
						}

    	   				if($row['booking_status']==0){ $image ='cancel1.png';  }
						
	   				    switch($row['booking_status'])
						{
							case '0': $b_type ='Pending';break;
							case '1': $b_type ='Unavailable';break;
							case '2': $b_type ='Confirmed';break;
						}
						/*if($row['booking_type']==1){ $b_type ='On Request';  }
    	   				if($row['booking_type']==0){ $b_type ='Pending';  }*/
						 ?>
        
        <tr>
        	<td style="text-align:center"><?=$i;?></td>
            <td><?=date('d-m-Y',strtotime($row['booking_date']))?></td>    
            <td><?=$row['propertycode']?></td>
            <td><?=date('d-m-Y', strtotime($row['date_from']))?></td>
            <td><?=dateDiff($row['date_from'],$row['date_to'])?></td>
            <td><?=date('d-m-Y',strtotime($row['date_to']))?></td>
            <td><?=$b_type?></td>    
            <td style="text-align:center">
                <a href="<?=APPLICATION_URL?>myaccount/displaybooking/bookingId/<?=$row['booking_id']?>">
                    <img src="<?=APPLICATION_URL;?>images/showreel.png"  height="22"   border='0' title='View' alt='View'>
                </a>
            </td>    
          
        </tr>
        <? } ?>
        </tbody>
    </table>

</div>

