<script type="text/javascript" src="<?=JS_URL?>main.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>

<div class="mws-form-inline"><div class="mws-form-row"><label>Enter Location:</label>
<div class="mws-form-item large"><?=$this->myform->address?><?=$this->myform->latitude?><?=$this->myform->longitude?> </div></div></div>
<div id="map_canvas" style="width:100%;height:400px;border: solid 1px #cccccc;"></div>

<!-- checkboxes for point of interests -->
<span style="font-weight:bold;">Check boxes to view local points of interest and services</span>
<div class = "check_bx">


    <!-- transport checkbox -->
    <div class = "checkbox_block">
    <input type="checkbox" name="transport"  id = "transport"/><label for="transport">Transport</label>
     
     <div style="margin-left:200px;">
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/airport-71.png" height="20" width="20"/>
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png" height="20" width="20"/>
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/travel_agent-71.png" height="20" width="20"/>
      </div>
    
    </div>
    
    <!-- bars and restaurants checkbox -->
    <div class = "checkbox_block">
    <input type="checkbox" name="bars"  id = "bars"/><label for="bars">Bars and restaurants</label>
    
    <div style="margin-left:200px;">
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/cafe-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png" height="20" width="20" />

    </div>
    
    </div>
    
    <!-- Tourist Attraction checkbox -->
    <div class = "checkbox_block">
    <input type="checkbox" name="tourist"  id = "tourist"/><label for="tourist">Tourist Attractions </label>
   
   	<div style="margin-left:200px;">
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/museum-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/art_gallery-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/camping-71.png" height="20" width="20" />
    </div>
    
   </div>
    
    <!-- shopping -->
    <div class = "checkbox_block">
    <input type="checkbox" name="shopping"  id = "shopping"/><label for="shopping">Shopping</label>
    
     <div style="margin-left:200px;">
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/jewelry-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png" height="20" width="20" />
        <img src="http://maps.gstatic.com/mapfiles/place_api/icons/electronics-71.png" height="20" width="20" />
    </div>
    	
    </div>

</div>

<!-- points of interest ends -->

