<div class="mws-panel-body" >
	<div  id="SigninBox">    
        <div><img src="<?=IMAGES_URL;?>/profile/no_owner_pic.jpg" width="200" height="150"></div>
        <div id="SigninLink">
            <ul>
                <li><a href="<?=APPLICATION_URL?>signup/profile">Edit Profile</a></li>
                <li><a href="<?=APPLICATION_URL?>signup/changepassword">Change Password</a></li>
                <li><a href="<?=APPLICATION_URL?>myaccount/addproperty">Add New Property</a></li>
                <li><a href="<?=APPLICATION_URL?>myaccount/propertyportfolio">Property Portfolio</a></li>
                <li><a href="<?=APPLICATION_URL?>signin/signout">Log Out</li>
    
           </ul>
        </div>
	</div>
</div>
