 
 <div style="width:85%; margin-left:7%;px" >
  <div class="mws-panel grid_8">
    <div class="mws-panel-header"><span class="mws-i-24 i-check"><?=$this->pageHeading?></span></div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="<?=$this->url(array('controller'=>'property', 'action'=>'processspeccat'), 'default', true)?>" method="post" novalidate="novalidate" class="mws-form">
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Category Name :</label><div class="mws-form-item large"><?=$this->myform->category?></div></div></div>
                <!--<div class="mws-form-inline"><div class="mws-form-row"><label>Description :</label><div class="mws-form-item large"><?=$this->myform->description?></div></div></div>-->              
                <div class="mws-form-inline"><div class="mws-form-row"><label>Status :</label><div class="mws-form-item large"><?=$this->myform->status?></div></div></div>
                
            <div class="mws-button-row"><input type="submit" tabindex="14" value="Submit" class="mws-button red" /></div>
        </form>
    </div>    	
</div> 
</div>
