 
 <div style="width:85%; margin-left:7%;px" >
  <div class="mws-panel grid_8">
    <div class="mws-panel-header"><span class="mws-i-24 i-check"><?=$this->pageHeading?></span></div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="<?=$this->url(array('controller'=>'property', 'action'=>'updatereview','reviewId'=>$this->reviewId), 'default', true)?>" method="post" novalidate="novalidate" class="mws-form">
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Check in date :</label><div class="mws-form-item large"><?=$this->myform->check_in?></div></div></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Name of Guest:</label><div class="mws-form-item large"><?=$this->myform->full_name?></div></div></div>
				<div class="mws-form-inline"><div class="mws-form-row"><label>Guest is From :</label><div class="mws-form-item large"><?=$this->myform->location?></div></div></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Customer Rating :</label><div class="mws-form-item large"><?=$this->myform->rating?></div></div></div>              
                <div class="mws-form-inline"><div class="mws-form-row"><label>Review Headline :</label><div class="mws-form-item large"><?=$this->myform->headline?></div></div></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Comment(Top Tip) :</label><div class="mws-form-item large"><?=$this->myform->comment?></div></div></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Review - Upto 1000 Characters :</label><div class="mws-form-item large"><?=$this->myform->review?></div></div></div>
                <div class="mws-form-inline"><div class="mws-form-row"><label>Status :</label><div class="mws-form-item large"><?=$this->myform->status?></div></div></div>                                                
	            <div class="mws-button-row"><input type="submit" tabindex="14" value="Submit" class="mws-button red" /></div>
        </form>
    </div>    	
</div> 
</div>
