<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>




<style type="text/css" title="currentStyle">
			@import "<?=CSS_URL_ADMIN?>demo_page.css";
			@import "<?=CSS_URL_ADMIN?>demo_table_jui.css";
			@import "<?=CSS_URL_ADMIN?>demo_table.css";
			@import "<?=CSS_URL_ADMIN?>jquery-ui-1.8.4.custom.css";
			@import "<?=CSS_URL_ADMIN?>psd.css";
		</style>
		<script type="text/javascript" language="javascript" src="<?=JS_URL_ADMIN?>jquery.js"></script>
		<script type="text/javascript" language="javascript" src="<?=JS_URL_ADMIN?>jquery.dataTables.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				oTable = $('#example').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );
		</script>









</head>

<body>
</body>
</html>