<?
global $mySession;
 
if(isset($mySession->errorMsg))
{
	//$mySession->errorMsg
	unset($mySession->errorMsg); 
}
?>
  
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- Apple iOS and Android stuff (do not remove) -->
<meta name="apple-mobile-web-app-capable" content="no" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,maximum-scale=1" />

<!-- Required Stylesheets -->
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/reset.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/text.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/fonts/ptsans/stylesheet.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/core/form.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/core/login.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/core/button.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL_ADMIN;?>css/mws.theme.css" media="screen" />

<!-- JavaScript Plugins -->
<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>js/jquery-1.7.1.min.js"></script>

<!-- jQuery-UI Dependent Scripts -->
<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>js/jquery-ui-effecs.min.js"></script>

<!-- Plugin Scripts -->
<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>plugins/placeholder/jquery.placeholder-min.js"></script>
<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>plugins/validate/jquery.validate-min.js"></script>

<!-- Login Script -->
<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>js/login.js"></script>
<link href="<?=IMAGES_URL;?>favicon.ico" type="image/x-icon" rel="icon" />
<title><?=SITE_NAME?></title>

</head>

<body>

    <div id="mws-login-wrapper">
        <div id="mws-login">
            <h1>Login</h1>
            <div class="mws-login-lock"><img src="<?=APPLICATION_URL_ADMIN;?>css/icons/24/locked-2.png" alt="" /></div>
            <div id="mws-login-form">
              <? echo $this->layout()->content; ?>  
            </div>
        </div>
    </div>

</body>
</html>
