<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="pageHeading"><?=$this->pageTitle?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="top" class="pHeading2" style="font-size:16px">

<?
if($this->sReturn!='2')
{
?>
Thank you for Signing Up.<br />
<? 
if($this->EmailAddress2!="")
{?>
A confirmation email has been Resent to you at : <?=$this->EmailAddress2?>

<? 
}
else if($this->EmailAddress1!="")
{
?>
A confirmation email has been sent to your update email : <?=$this->EmailAddress1?>

<? } 
else
{?>
A confirmation email has been sent to you at: <?=$this->EmailAddress?>
<? } ?><br />
<br />
<img alt="" src="<?=IMAGES_URL?>message.png">
<br />
Click the link in that email to confirm your address and activate your account.
<br />
<span><a href="<?=APPLICATION_URL?>signup/success/userId/<?=$this->user_id?>">Resend Confirmation Message </a></span><span style="border-right:1px solid #999">&nbsp;</span>
<span><a href="javascript:onclick=show();" >Change Email Address</a></span>

<br />
<div id="changeEmail" style="border:1px solid #999999;display:none; height:130px; width:270px; margin-top:-170px;
 margin-left:500px;z-index:1; position:relative">
 <form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'signup', 'action'=>'success',
 'changeEmail'=>$this->user_id), 'default', true)?>" method="post">
<table border="0" style="background-color:#f7f7f7;height:130px; width:270px;" >
<tr>
<td valign="top" align="center">
Enter New Email Address :
</td>
</tr>
<tr>
<td valign="top" align="center">
<input type="text" name="email" id="email" class="textInput"  style="margin-left:10px"/>
</td>
</tr>
<tr>
<td valign="top" align="center"  >
<input type="submit" name="submit" id="submit" value="Submit" />&nbsp;&nbsp;&nbsp;
<input type="button" name="cancel" id="cancel"  value="cancel" onclick="hide();"/>
</td>
</tr>
</table>
</form>
</div>
<?
}
if($this->sReturn=='1')
{
?>
Your Payment process completed successfully. Thank you.
<?
}
if($this->sReturn=='2')
{
?>
Your Payment process failed. Please Try Again.
<?
}
?>

</td>
</tr>
</table>

<script type="text/javascript">
function show()
{
	
	document.getElementById('changeEmail').style.display='block';
}
function hide()
{
	
	document.getElementById('changeEmail').style.display='none';
}
</script>