<form  class="mws-form" name="myform" id="myform" action="" method="post"  >

    <div class="mws-form-row">
        <div class="mws-form-item large">
            <input type="text" name="admin_username" class="mws-login-username mws-textinput required" placeholder="login id" />
        </div>
    </div>
    <div class="mws-form-row">
        <div class="mws-form-item large">
            <input type="password" name="admin_password" class="mws-login-password mws-textinput required" placeholder="password" />
        </div>
    </div>
    <!--<div class="mws-form-row mws-inset">
        <ul class="mws-form-list inline">
            <li><input type="checkbox" /> <label>Remember me</label></li>
        </ul>
    </div>-->
    <div class="mws-form-row">
        <input type="submit" value="Login" class="mws-button green mws-login-button" />
    </div>
</form>
                 