<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="center" valign="middle" height="410"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'index', 'action'=>'login'), 'default', true)?>" method="post"><table width="40%" cellpadding="5" cellspacing="5">
<tr>
<td width="22%" align="left" valign="top"><strong>Username:</strong></td>
<td width="78%" align="left" valign="top"><?=$this->myform->admin_username?></td>
</tr>
<tr>
<td align="left" valign="top"><strong>Password:</strong></td>
<td align="left" valign="top"><?=$this->myform->admin_password?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Login" id="Login" value="Login" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>

<script>
window.onload=document.getElementById('admin_username').focus();
</script>
