<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle">
<form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'blog', 'action'=>'saveblog'), 'default', true)?>" method="post">
<table width="100%" cellpadding="2" cellspacing="2">

<tr>
<td width="12%" align="left" valign="top">Title :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->title?></td>
</tr>
<tr>
<td align="left" valign="top">Description :</td>
<td align="left" valign="middle"><?=$this->myform->description?></td>
</tr>
<tr>
<td align="left" valign="top">Status :</td>
<td align="left" valign="middle"><?=$this->myform->status?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>

</table></form></td>
</tr>
</table>
