<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'users', 'action'=>'updateadmin','adminId'=>$this->adminId), 'default', true)?>" method="post"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td width="12%" align="left" valign="top">First Name :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->first_name?></td>
</tr>
<tr>
<td align="left" valign="top">Last Name :</td>
<td align="left" valign="middle"><?=$this->myform->last_name?></td>
</tr>
<tr>
<td align="left" valign="top">Email Address :</td>
<td align="left" valign="middle"><?=$this->myform->email_address?></td>
</tr>
<tr>
<td align="left" valign="top">Username :</td>
<td align="left" valign="middle"><?=$this->myform->username?></td>
</tr>
<tr>
<td align="left" valign="top">Status :</td>
<td align="left" valign="middle"><?=$this->myform->admin_status?></td>
</tr>
<tr>
<td align="left" valign="top">Change Password : </td>
<td align="left" valign="middle"><input type="checkbox" name="changePass" id="changePass" onclick="showPassDiv(this);" value="1" /></td>
</tr>
<tr>
<td align="left" valign="top" colspan="2"><div id="ChangePassDiv" style="display:none;">
	<table width="100%" cellpadding="2" cellspacing="2">
    <tr>
    <td width="12%" align="left" valign="top">Password :</td>
    <td width="88%" align="left" valign="middle"><?=$this->myform->password_o?></td>
    </tr>
    <tr>
    <td align="left" valign="top">Confirm Password :</td>
    <td align="left" valign="middle"><?=$this->myform->password_c?></td>
    </tr>
    </table></div>
</td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
<script language="javascript">
function showPassDiv(obj)
{
	if(obj.checked==true)
	{
		document.getElementById('ChangePassDiv').style.display="block";
	}
	else
	{
		document.getElementById('ChangePassDiv').style.display="none";	
	}
}
</script>
<?
if(isset($_REQUEST['ChangePass']))
{
?>
<script language="javascript">
document.getElementById('changePass').checked=true;
document.getElementById('ChangePassDiv').style.display="block";
</script>
<?	
}
?>
