<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr> 
<tr>
<td align="left" valign="top"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'test', 'action'=>'save'), 'default', true)?>" method="post" enctype="multipart/form-data">
<table width="100%" cellpadding="2" cellspacing="2">

<tr>
<td align="left" valign="top">Business Listing File </td><td align="left" valign="top"> <?=$this->myform->excelfile?></td>
</tr>

<tr> 
<td align="left" valign="top">Compressed File for Images </td><td align="left" valign="top"> <?=$this->myform->zipfile?></td></tr>
<tr><td align="left" valign="top" colspan="2"> <input type="submit" name="Submit" value="Submit" /> </td> </tr>
</table>


</form></td>
</tr>
</table>