<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" width="21"><img src="<?=IMAGES_URL?>box_top1.png" border="0" /></td>
<td align="left" valign="middle" style="background-image:url(<?=IMAGES_URL?>box_top2.png);background-repeat:repeat-x;" class="pageHeading"><?=$this->pageTitle?></td>
<td align="left" valign="top" width="21"><img src="<?=IMAGES_URL?>box_top3.png" border="0" /></td>
</tr>
<tr>
<td align="left" valign="top" colspan="3" class="main_content_area"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'photo', 'action'=>'uploadphoto'), 'default', true)?>" method="post" enctype="multipart/form-data"><table width="100%" cellpadding="4" cellspacing="4">
<tr>
<td align="right" valign="top" colspan="3"><a href="<?=APPLICATION_URL?>photo/gallery" style="font-weight:bold;">Back</a></td>
</tr>
<tr>
<td width="14%" align="left" valign="top">Photo title : <span class="error">*</span></td>
<td align="center" valign="top" width="5%"><strong>:</strong></td>
<td width="81%" align="left" valign="middle"><?=$this->myform->photo_title?></td>
</tr>
<tr>
<td align="left" valign="top">Photo : <span class="error">*</span></td>
<td align="center" valign="top"><strong>:</strong></td>
<td align="left" valign="middle"><?=$this->myform->photo_path?></td>
</tr>
<tr>
<td align="left" valign="top" colspan="2">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Upload Photo" id="Upload Photo" value="Upload Photo" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>