<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
    </div>

    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix ">
            <ul>
               <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" onclick="deleteitem()">Delete</a></li>
            </ul>
        </div>
        <!--<table class="mws-table">-->
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <th width="5%" align="center"><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>
                    <th width="15%">Sender</th>
                    <th width="25%">Subject</th>
                    <th width="15%">Date</th>
                     <th width="5%">Action</th>
               </tr>
            </thead>
            <tbody>
                <?
                $i=0;
                foreach($this->ResData as $row)
                {
                    $start++;$i++;
                    if($cClass=="gradeX odd")
                        {$cClass="gradeX even";}
                    else
                        {$cClass="gradeX odd";}	
                    ?>
                        <tr class="gradeX">
                            <td style="text-align:center"><?=$i;?></td>
                            <td style="text-align:center">
                                <input name='check<?=$i;?>' id='check<?=$i;?>' value='<?=$row['message_id'];?>' 
                                    onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                                    
                                <script> 
                                    $(document).ready(function(){
                                        $('#bcdel').html(''); 
                                        document.getElementById('deletebcchk').checked = false;
                                    });
                                </script>
                            </td>
                             <td ><?=$row['sender_name'];?></td>
                              <td ><?=$row['message_subject'];?></td>
	                          <td ><?=date(DATEFORMAT,strtotime($row['date_message_sent']))?></td>
                              <td style="text-align:center">
                                <a href="<?=APPLICATION_URL_ADMIN;?>msgs/viewmsgs/msgsId/<?=$row['message_id'];?>" class="mws-ic-16 ic-email-open mws-tooltip-s" title = "view" style="width:25px;float:left;">&nbsp;&nbsp;
<!--                                        <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/32/application_view_icons.png" height="16" width="16"   border='0' title='View' alt='View'>-->
                                </a>
                                <a href="<?=APPLICATION_URL_ADMIN;?>msgs/compose/rId/<?=$row['sender_id'];?>" class="mws-ic-16 ic-email mws-tooltip-s" title = "reply" style="width:25px;float:left;">&nbsp;&nbsp;</a>
                                
                            </td>                            
                        </tr>
                    <?
                }
                ?>
            </tbody>
        </table>
    </div>    	
</div>
<script>
function deleteitem()
{
	var r= "";
	var s="";
	var selected=false;
	for(var i=1;document.getElementById('check'+i);i++){
		if(document.getElementById('check'+i).checked==true){	
			r += document.getElementById('check'+i).value+"|";
			selected = true;
		}
	}	
	
	r += '0';
	if(selected)
	{
		var confirmation = confirm("Are you sure want to delete ?");
		if(confirmation!=true){
			return false;
		}	
		
		$.ajax({ url: "<?=APPLICATION_URL_ADMIN."msgs/deletemsgs"?>",
		type: "POST",
		data: ({Id:r}),
		cache: false,
		success: function(data){
				alert('Selected records have been deleted successfully.');		
			   window.location.href=window.location.href;
		}});
	} else {
		alert('Please choose a record to delete.');
	}
}


 
function checkall(thisid)
{
  for(var i=1;document.getElementById('check'+i);i++)
  	{
  		if(document.getElementById(thisid.id).checked==true){document.getElementById('check'+i).checked = true;}
  		if(document.getElementById(thisid.id).checked==false){document.getElementById('check'+i).checked = false;}
	}	
}
</script>