<?

if($this->varsuccess == 0)
{
	?>

<script type="text/javascript">
$(document).ready(function(e) {

 jQuery.validator.addMethod("equals", function(value, element) { 
    return ($("#new_password").val() == value); 
  }, "Password mismatches");

});
</script>

	

<div id="InnerPages">
   <div> 


    <div class="mws-panel-body" style="height:420px">

      	  <form name="myform" id="mws-validate"  method="post" novalidate="novalidate" class="mws-form" >
           <div class="mws-form-inline"><div class="mws-form-row"><label>Current Password :</label><div class="mws-form-item small"><?=$this->myform->o_password?></div></div></div>
           <div class="mws-form-inline"><div class="mws-form-row"><label>New Password :</label><div class="mws-form-item small"><?=$this->myform->new_password?></div></div></div>
            <div class="mws-form-inline"><div class="mws-form-row"><label>Confirm Password :</label><div class="mws-form-item small"><?=$this->myform->confirm_new_password?></div></div></div>
            <div class="mws-button-row">
            <input type="submit" value="submit" class="mws-button">
			</div>
		</form> 
   </div>
   </div>
<?
}
?>
