    <div class="mws-panel-body">
    <form name="myform" id="mws-validate" method="post"  novalidate="novalidate" class="mws-form" >
        	 <div class="mws-form-inline"><div class="mws-form-row"><label>Email</label><div class="mws-form-item small"><?=$this->myform->email_address?> </div></div></div>
         
             <div class="mws-button-row2">
             	<input type="submit" value="Submit" class="mws-button" />
                 <a href = '<?=APPLICATION_URL?>signin'  style="border:0px" >Log in</a>
	            <a href = '<?=APPLICATION_URL?>signup'  >Register</a>
             </div>
    </form>    

	</div>
