<?
global $mySession;
?>
<script type="text/javascript">
$(document).ready(function(e) {

 jQuery.validator.addMethod("equals", function(value, element) { 
    return ($("#new_password").val() == value); 
  }, "Password mismatches");


});
</script>

<?
if($this->requestId != 'Expire' || $this->varsuccess == 0)
{
?>	
 
    <div class="mws-panel-body">

      	  <form name="myform" id="mws-validate"  method="post" novalidate="novalidate" class="mws-form" >
			  <!--<div class="mws-form-inline"><div class="mws-form-row"><label>Current Password :</label><div class="mws-form-item medium"><?=$this->myform->o_password?></div></div></div>-->
             <div class="mws-form-inline"><div class="mws-form-row"><label>Password :</label><div class="mws-form-item medium"><?=$this->myform->new_password?></div></div></div>
            <div class="mws-form-inline"><div class="mws-form-row"><label>Confirm Password :</label><div class="mws-form-item medium"><?=$this->myform->confirm_new_password?></div></div></div>
            <div class="mws-button-row1">
            <input type="submit" value="submit" class="mws-button" style="margin-left:20px;">
			</div>
		</form> 
   </div>
 
<?
}
else
{
?>
 
    	<div class="mws-form-message error" id="mws-validate-error">
        	The Page you requested has been expired!!
        </div>
 
<?
}
?>


		


