<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'pages', 'action'=>'updatecategory','categoryId'=>$this->categoryId), 'default', true)?>" method="post"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td width="12%" align="left" valign="top">Category Name :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->cat_name?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
