<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'services', 'action'=>'updatesubcate','subcateid'=>$this->subcateid), 'default', true)?>" method="post" enctype="multipart/form-data"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td width="12%" align="left" valign="top">Subcategory Name :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->subcate_name?></td>
</tr>

<tr>
<td width="12%" align="left" valign="top">Choose Category :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->category?></td>
</tr>

<tr>
<td align="left" valign="top">Category Icon :</td>
<td align="left" valign="middle"><?=$this->myform->subcate_image?></td>
</tr>

<tr>

<td align="left" valign="middle"><?=$this->myform->old_subcat_image?></td>
</tr>

<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
