<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'services', 'action'=>'updatecategory','categoryId'=>$this->categoryId), 'default', true)?>" method="post" enctype="multipart/form-data"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td width="12%" align="left" valign="top">Category Name :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->cat_name?></td>
</tr>
<tr>
<td align="left" valign="top">Category Icon :</td>
<td align="left" valign="middle"><?=$this->myform->cat_image?><?=$this->myform->old_cat_image?></td>
</tr>
<?
if($this->catImage!="" and file_exists(SITE_ROOT.'images/categories/'.$this->catImage))
{
?>
<tr>
<td align="left" valign="top"></td>
<td align="left" valign="top"><a href="<?=APPLICATION_URL?>download.php?download_file=<?='images/categories/'.$this->catImage?>">View/Download Category Icon</a></td>
</tr>
<?
}
?>
<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
