<script type="text/javascript">
function is_valid_zip(e,obj)
{
	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
	var zip= document.getElementById('zipcode').value;
	//alert(keypressed);
	if(keypressed!="48" &&  keypressed!="49" && keypressed!="50" && keypressed!="51" && keypressed!="52" && keypressed!="53" && keypressed!="54" && keypressed!="55" && keypressed!="56" && keypressed!="57" && keypressed!="8" && keypressed!="46"  && keypressed!="37" && keypressed!="39" && keypressed!="9" )
	{ //alert(keypressed);
 		return false;
	}

}
</script>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr>
<tr>
<td align="center" valign="middle"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'cities', 'action'=>'savecities'), 'default', true)?>" method="post"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td width="12%" align="left" valign="top">City Name :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->name?></td>
</tr>

<tr>
<td width="12%" align="left" valign="top">Zip Code :</td>
<td width="88%" align="left" valign="middle"><?=$this->myform->zipcode?></td>
</tr>

<tr>
<td align="left" valign="top">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Submit" id="Submit" value="Submit" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
