<!-- Required Stylesheets -->

<link rel="stylesheet" type="text/css" href="<?= APPLICATION_URL; ?>css/mws/form.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?= APPLICATION_URL; ?>css/mws/fileinput.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?= CSS_URL ?>jquery-ui.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?= APPLICATION_URL; ?>css/mws/error.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?= APPLICATION_URL_ADMIN; ?>plugins/tipsy/tipsy.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?= APPLICATION_URL_ADMIN; ?>plugins/chosen/chosen.css" media="screen" />
<!-- JavaScript Plugins -->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/jquery.mousewheel-min.js"></script>
<script type="text/javascript" src="<?= JS_URL ?>ajaxfileupload.js"></script>
<!-- jQuery-UI Dependent Scripts -->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/jquery-ui.js"></script>
<!--<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/spinner/ui.spinner.min.js"></script>-->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/timepicker/timepicker-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/jquery.ui.touch-punch.min.js"></script>

<!-- Plugin Scripts -->
<!--<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/imgareaselect/jquery.imgareaselect.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/duallistbox/jquery.dualListBox-1.3.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/jgrowl/jquery.jgrowl-min.js"></script>-->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/fileinput/js/jQuery.fileinput.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/fullcalendar/fullcalendar.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/datatables/jquery.dataTables-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/prettyphoto/js/jquery.prettyPhoto-min.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/flot/excanvas.min.js"></script>
<![endif]-->
<!--<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/flot/jquery.flot.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/flot/jquery.flot.pie.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/flot/jquery.flot.stack.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/flot/jquery.flot.resize.min.js"></script>-->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/colorpicker/colorpicker-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/tipsy/jquery.tipsy-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/sourcerer/Sourcerer-1.2-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/placeholder/jquery.placeholder-min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/validate/jquery.validate-min.js"></script>
<!--<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/validate/jquery.validate"></script>-->

<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/elrte/js/elrte.min.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>plugins/elfinder/js/elfinder.min.js"></script>

<!-- Core Script -->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/mws.js"></script>

<!-- Themer Script (Remove if not needed) -->
<!--<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/themer.js"></script>-->

<!-- Demo Scripts (remove if not needed) -->
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/demo.front.js"></script>
<script type="text/javascript" src="<?= APPLICATION_URL_ADMIN; ?>js/demo.formelements.js"></script>


<link type="text/css" rel="stylesheet" href="<?= APPLICATION_URL_ADMIN ?>plugins/httpadder/css/httpadder.css" />
<script src="<?= APPLICATION_URL_ADMIN ?>plugins/httpadder/js/jQuery.Httpadder.js" type="text/javascript"></script>