<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" width="21"><img src="<?=IMAGES_URL?>box_top1.png" border="0" /></td>
<td align="left" valign="middle" style="background-image:url(<?=IMAGES_URL?>box_top2.png);background-repeat:repeat-x;" class="pageHeading"><?=$this->pageTitle?></td>
<td align="left" valign="top" width="21"><img src="<?=IMAGES_URL?>box_top3.png" border="0" /></td>
</tr>
<tr>
<td align="left" valign="top" colspan="3" class="main_content_area">
<form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'video', 'action'=>'uploadvideo'), 'default', true)?>" method="post" enctype="multipart/form-data"><table width="100%" cellpadding="4" cellspacing="4">
<tr>
<td align="right" valign="top" colspan="3"><a href="<?=APPLICATION_URL?>video/gallery" style="font-weight:bold;">Back</a></td>
</tr>
<tr>
<td width="14%" align="left" valign="top">Video title : <span class="error">*</span></td>
<td align="center" valign="top" width="5%"><strong>:</strong></td>
<td width="81%" align="left" valign="middle"><?=$this->myform->video_title?></td>
</tr>
<tr>
<td align="left" valign="top">Upload From : <span class="error">*</span></td>
<td align="center" valign="top"><strong>:</strong></td>
<td align="left" valign="middle"><?=$this->myform->path_type?><br />
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top">
<div id="FromComputer" style="display:block;"><?=$this->myform->video_path?></div>
<div style="display:block;font-size:11px;" id="MessageDiv">Please upload only flv extension video files</div>
<div id="FromYouTube" style="display:none;"><?=$this->myform->you_tube_url?></div>
</td>
</tr>
</table></td>
</tr>
<tr>
<td align="left" valign="top" colspan="2">&nbsp;</td>
<td align="left" valign="top"><input type="submit" name="Upload Video" id="Upload Video" value="Upload Video" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>
<script language="javascript">
function setType(vtype)
{
	if(vtype==1)
	{
		document.getElementById('FromComputer').style.display="block";
		document.getElementById('MessageDiv').style.display="block";
		document.getElementById('FromYouTube').style.display="none";
		
	}
	else
	{
		document.getElementById('FromComputer').style.display="none";
		document.getElementById('MessageDiv').style.display="none";
		document.getElementById('FromYouTube').style.display="block";
	}
}
<?
if(isset($_REQUEST['path_type']))
{
?>
setType('<?=$_REQUEST['path_type']?>')
<?	
}
?>
</script>