<?  ?>
<p class="staticPage" style="text-align: center">"Oops, I screwed up and you discovered my fatal flaw.<br> 
Well, we're not all perfect, but we try.  Can you try this again <br> or maybe visit our 
<a title="Our Site" href="<?php echo APPLICATION_URL; ?>">Home Page</a> to start fresh.<br>
We'll do better next time."</p>
<div class="errorPageMain">

</div>

 
 
<style>

.errorPageMain
{
	width:100%;
	height:500px;
	background-position:center center;
	background-image:url('<?=IMAGES_URL?>page_not_found.jpg');
	background-repeat:no-repeat;
}
h1.pageTitles
{
	text-align:center !important;
	padding:0  !important;
 }
</style>
