 
<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="" method="post" novalidate="novalidate" class="mws-form" enctype="multipart/form-data" >
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            <div class="mws-form-inline"><div class="mws-form-row"><label>Property Code:</label><div class="mws-form-item medium"><?=$this->myform->propertycode?></div></div></div>
            <div class="mws-form-inline"><div class="mws-form-row"><label>Status:</label><div class="mws-form-item medium"><?=$this->myform->status?></div></div></div>                 
            <div class="mws-button-row">
                <input type="submit" value="Submit" class="mws-button red" />
            </div>
        </form>
    </div>    	
</div>
