<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		
		
		<title>DataTables example</title>
		
       <?
	  
	   include SITE_ROOT.'admin/application/layouts/scripts/contents.phtml';
	   ?>
        
	</head>
	<body id="dt_example">
		<div id="container">
		  <div class="demo_jui">
		    <table width="796" border="0" cellpadding="0" cellspacing="0" class="display " style="background-color:#FFFFFF" id="example">
	<thead>
		<tr >
			<th height="38"  class="border">Rendering engine</th>
			<th  class="border" align="center">Browser</th>
			<th  class="border" align="center">Platform(s)</th>
			<th  class="border" align="center">Engine version</th>
			<th  class="border-l" align="center">CSS grade</th>
		</tr>
	</thead>
	<tbody >
		<tr class="gradeX">
			<td  class="border">Trident</td>
			<td class="border">Internet
				 Explorer 4.0</td>
			<td class="border" align="center">Win 95+</td>
			<td class="center border" align="center">4</td>
			<td class="center border-l" align="center">X</td>
		</tr>
		<tr class="gradeC">
			<td  >Trident</td>
			<td>Internet
				 Explorer 5.0</td>
			<td>Win 95+</td>
			<td class="center">5</td>
			<td class="border-l">C</td>
		</tr>
		<tr class="gradeA">
			<td height="26">Trident</td>
			<td>Internet
				 Explorer 5.5</td>
			<td>Win 95+</td>
			<td class="center">5.5</td>
			<td class="center border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="26">Trident</td>
			<td>Internet
				 Explorer 6</td>
			<td>Win 98+</td>
			<td class="center">6</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="28">Trident</td>
			<td>Internet Explorer 7</td>
			<td>Win XP SP2+</td>
			<td class="center">7</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="24">Trident</td>
			<td>AOL browser (AOL desktop)</td>
			<td>Win XP</td>
			<td class="center">6</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Firefox 1.0</td>
			<td class="border" align="center">Win 98+ / OSX.2+</td>
			<td class="border" align="center">1.7</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td  height="38"   class="border">Gecko</td>
			<td class="border" align="center">Firefox 1.5</td>
			<td class="border" align="center">Win 98+ / OSX.2+</td>
			<td class="border" align="center">1.8</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Firefox 2.0</td>
			<td class="border" align="center">Win 98+ / OSX.2+</td>
			<td class="border" align="center">1.8</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Firefox 3.0</td>
			<td class="border" align="center">Win 2k+ / OSX.3+</td>
			<td class="border" align="center">1.9</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Camino 1.0</td>
			<td class="border" align="center">OSX.2+</td>
			<td class="border" align="center">1.8</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="40" class="border">Gecko</td>
			<td class="border" align="center">Camino 1.5</td>
			<td class="border" align="center">OSX.3+</td>
			<td class="border" align="center">1.8</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Netscape 7.2</td>
			<td class="border" align="center">Win 95+ / Mac OS 8.6-9.2</td>
			<td class="border" align="center">1.7</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Netscape Browser 8</td>
			<td class="border" align="center">Win 98SE+</td>
			<td class="border" align="center">1.7</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Netscape Navigator 9</td>
			<td class="border" align="center">Win 98+ / OSX.2+</td>
			<td class="border" align="center">1.8</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Mozilla 1.0</td>
			<td class="border" align="center">Win 95+ / OSX.1+</td>
			<td class="border" align="center">1</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border" align="center">Mozilla 1.1</td>
			<td class="border" align="center">Win 95+ / OSX.1+</td>
			<td class="border" align="center">1.1</td>
			<td class="border-l" align="center">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border">Mozilla 1.2</td>
			<td class="border">Win 95+ / OSX.1+</td>
			<td class="border">1.2</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border">Mozilla 1.3</td>
			<td class="border">Win 95+ / OSX.1+</td>
			<td class="border">1.3</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38" class="border">Gecko</td>
			<td class="border">Mozilla 1.4</td>
			<td class="border">Win 95+ / OSX.1+</td>
			<td class="border">1.4</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Mozilla 1.5</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.5</td>
			<td class="border-l ">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Mozilla 1.6</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.6</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Mozilla 1.7</td>
			<td>Win 98+ / OSX.1+</td>
			<td class="center">1.7</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Mozilla 1.8</td>
			<td>Win 98+ / OSX.1+</td>
			<td class="center">1.8</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Seamonkey 1.1</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td height="38">Gecko</td>
			<td>Epiphany 2.20</td>
			<td>Gnome</td>
			<td class="center">1.8</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 1.2</td>
			<td>OSX.3</td>
			<td class="center">125.5</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 1.3</td>
			<td>OSX.3</td>
			<td class="center">312.8</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 2.0</td>
			<td>OSX.4+</td>
			<td class="center">419.3</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 3.0</td>
			<td>OSX.4+</td>
			<td class="center">522.1</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>OmniWeb 5.5</td>
			<td>OSX.4+</td>
			<td class="center">420</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>iPod Touch / iPhone</td>
			<td>iPod</td>
			<td class="center">420.1</td>
			<td class="border-l">A</td>
		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>S60</td>
			<td>S60</td>
			<td class="center">413</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 7.0</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 7.5</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 8.0</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 8.5</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.0</td>
			<td>Win 95+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.2</td>
			<td>Win 88+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.5</td>
			<td>Win 88+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera for Wii</td>
			<td>Wii</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Nokia N800</td>
			<td>N800</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Nintendo DS browser</td>
			<td>Nintendo DS</td>
			<td class="center">8.5</td>
			<td class="center">C/A<sup>1</sup></td>
		</tr>
		<tr class="gradeC">
			<td>KHTML</td>
			<td>Konqureror 3.1</td>
			<td>KDE 3.1</td>
			<td class="center">3.1</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeA">
			<td>KHTML</td>
			<td>Konqureror 3.3</td>
			<td>KDE 3.3</td>
			<td class="center">3.3</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeA">
			<td>KHTML</td>
			<td>Konqureror 3.5</td>
			<td>KDE 3.5</td>
			<td class="center">3.5</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeX">
			<td>Tasman</td>
			<td>Internet Explorer 4.5</td>
			<td>Mac OS 8-9</td>
			<td class="center">-</td>
			<td class="center">X</td>
		</tr>
		<tr class="gradeC">
			<td>Tasman</td>
			<td>Internet Explorer 5.1</td>
			<td>Mac OS 7.6-9</td>
			<td class="center">1</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeC">
			<td>Tasman</td>
			<td>Internet Explorer 5.2</td>
			<td>Mac OS 8-X</td>
			<td class="center">1</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeA">
			<td>Misc</td>
			<td>NetFront 3.1</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeA">
			<td>Misc</td>
			<td>NetFront 3.4</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">A</td>
		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Dillo 0.8</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">X</td>
		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Links</td>
			<td>Text only</td>
			<td class="center">-</td>
			<td class="center">X</td>
		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Lynx</td>
			<td>Text only</td>
			<td class="center">-</td>
			<td class="center">X</td>
		</tr>
		<tr class="gradeC">
			<td>Misc</td>
			<td>IE Mobile</td>
			<td>Windows Mobile 6</td>
			<td class="center">-</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeC">
			<td>Misc</td>
			<td>PSP browser</td>
			<td>PSP</td>
			<td class="center">-</td>
			<td class="center">C</td>
		</tr>
		<tr class="gradeU">
			<td>Other browsers</td>
			<td>All others</td>
			<td>-</td>
			<td class="center">-</td>
			<td class="center">U</td>
		</tr>
	</tbody>
	<tfoot>
		<tr >
			<th height="40" class="border">Rendering engine</th>
			<th class="border">Browser</th>
			<th class="border">Platform(s)</th>
			<th class="border">Engine version</th>
			<th class="border-l">CSS grade</th>
		</tr>
	</tfoot>
</table>
			</div>
		  <h1>&nbsp;</h1>
		</div>
	</body>
</html>