<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="left" valign="top" class="main_heading"><?=$this->pageHeading?></td>
</tr>
<tr>
<td align="left" valign="top">&nbsp;</td>
</tr> 
<tr>
<td align="center" valign="top"><form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'system', 'action'=>'updatemanagead'), 'default', true)?>" method="post" enctype="multipart/form-data"><table width="100%" cellpadding="2" cellspacing="2">
<tr>
<td align="left" valign="top" width="208">Image :</td>
<td width="953" align="left" valign="top"><?=$this->myform->advertise_image?>
<?
if($this->default_ad_image!="")
{
?>
<div style="clear:both;padding-top:5px;">
<img src="<?=APPLICATION_URL?>image.php?image=images/adimage/<?=$this->default_ad_image?>&height=200&width=200" border="0" />
</div>
<?	
}
?>
</td>
</tr>
<tr><td align="left" valign="top" colspan="2">&nbsp;</td></tr>
<tr>
<td align="left" valign="top">Link :</td>
<td align="left" valign="top"><?=$this->myform->ad_url?></td>
</tr>
<tr>
<td align="left" colspan="2" valign="top"><input type="submit" name="Save Ad" id="Save Ad" value="Save Ad" class="myButton" /></td>
</tr>
</table></form></td>
</tr>
</table>