<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Change Password</span>
    </div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="" method="post" novalidate="novalidate" class="mws-form">


            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Username :</label>
                    <div class="mws-form-item large">
                        <?= $this->adminData['admin_username'] ?>
                    </div>
                </div>
                <div class="mws-form-row">
                    <label>New Password :</label>
                    <div class="mws-form-item large">
                        <?= $this->myform->new_password ?><!--<input type="text" class="mws-textinput required" name="reqField">-->
                    </div>
                </div>
                <div class="mws-form-row">
                    <label>Confirm Password :</label>
                    <div class="mws-form-item large">
                        <?= $this->myform->confirm_new_password ?><!--<input type="text" class="mws-textinput required" name="reqField">-->
                    </div>
                </div>
            </div>
            <div class="mws-button-row">
                <input type="submit" class="mws-button red" value="Submit">
            </div>
        </form>
    </div>    	
</div>