<?
global $mySession;

?>
<style>
#SizeOfParty {
    margin-bottom: 10px;
}
.LightPanel {
    background-color: #F4F8FB;
    border: 0 none;
    margin: 10px;
    padding: 10px;
   
}
.BookingDetailsLabel {
    float: left;
    font-weight: bold;
    width: 120px;
}

.discount-code{
    -moz-box-sizing: border-box;
    background-color: #FFFFFF;
    border: 1px solid #CDCDCD;
    box-shadow: 0 1px 3px rgba(128, 128, 128, 0.1) inset;
    color: #323232;
    margin: 0;
    outline: medium none;
    padding: 6px 7px;
}

.ChangeDetails {
    float: left;
    margin: 5px 0;
    width: 100%;
}
a {
    color: #D74B14;
    text-decoration: underline;
}
#error
{
	color:#903;
	display:none;
	width:500px;
}
.quote-row-right {
    text-align: right;
    vertical-align: top;
}
table
{
	margin:0px;!important;
}
#cost
{
text-decoration:line-through;	
}
</style>
<div class="LightPanel" id="Tabs_discount-box">
				
                             <h3>Booking</h3>
                               
                                <div id="discount-box">
                                    <span style="color: #807E7E">Booking Suceffully !</span>
                                    </div>
                                
                                <br class="clear">
                            
			</div>